server:
  port:8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/akshaypalshikar/spring-config-prop-demo
          username : aksmakesit@gmail.com
          password :  ${git.password}
